### ISSUE TITLE
Version 1_0_6 does not include WindowsVoice.dll

### ISSUE THREAD

**Issue by ExRed** [Osmodium/PathfinderTextToSpeechMod#19]
The latest release-zip ([SpeechMod_1_0_6.zip](https://github.com/Osmodium/PathfinderTextToSpeechMod/releases/tag/1.0.6)) doesn not include the required "WindowsVoice.dll" which makes the mod fail to load. 

This will not be an issue when updating 1_0_5 to 1_0_6 by overwriting files, because the missing file already exists. 

Solution: Put WindowsVoice.dll from 1_0_5 into the path of 1_0_6.

**Comment by Osmodium** [comment]
Ah shoot, made the zip file wrong.
Thanks for reporting, looking into it now.

**Comment by Osmodium** [comment]
Should be fixed in 1_0_6 now too.
