### ISSUE TITLE
Windows Natural Voices Not Showing Up

### ISSUE THREAD

**Issue by ttmullins** [Osmodium/PathfinderTextToSpeechMod#23]
I have installed windows natural voices through the windows settings but i do not see any additional voices appearing in the mod. Can you please let me know if im doing something wrong?

**Comment by Osmodium** [comment]
Hi @ttmullins 
There is a "guide" in how to accomplish this on the [mod page](https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/241/?tab=description) on NexusMods.
(https://www.ghacks.net/2018/08/11/unlock-all-windows-10-tts-voices-system-wide-to-get-more-of-them/)

**Comment by ttmullins** [comment]
Thank you!!

**Comment by Osmodium** [comment]
No worries, hope you got it to work.
